apiVersion: apps/v1
kind: Deployment
metadata:
  name: payroll-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payroll-pod
  template:
    metadata:
      labels:
        app: payroll-pod
    spec:
      containers:
      - name: payroll-container
        image: tscpayroll.azurecr.io/payrolltsc:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
